[package]
name = "bassment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
actix-web = "4"
diesel = { version = "1.4", features = ["postgres"] }
diesel_migrations = "1.4"
r2d2 = "0.8"
