#!/bin/bash

# Runs the backend (API-only) for development.

set -e
cd "$(dirname $0)/.."

# --api-only:   Only run API server (don't serve bundled frontend on /)
# --allow-cors: Allow all CORS requests (don't use in production!)
cargo run -- --api-only --allow-cors $*
