name: Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build project
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features
